---
title: "hw 5"
author: "Wurongyan Zhang"
date: "11/5/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## problem 1

```{r}
library(tidyverse)
library(ggplot2)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r,warning=FALSE}
summary(is.na(iris_with_missing)) %>% 
  knitr::kable()
```

As we can see from the summary above, the data set iris_with_missing has 20 missing values in each of the 5 variables.

```{r}
na_func = function(x){
  if(is.character(x)){
    x=replace_na(x,"virginica")
  }
  else if(is.numeric(x)){
    x=replace_na(x, round(mean(x,na.rm=TRUE),digits=1))
  }
  x
}

iris=map_dfr(iris_with_missing,na_func)

summary(is.na(iris))%>% 
  knitr::kable()
```

As we can see from the second table, there are no missing values after the function.

## problem 2

```{r,message=FALSE}
file = list.files("data")

file_data = purrr::map_dfr( str_c("./data/",file), read_csv) %>% 
 janitor::clean_names() %>% 
  mutate(file_name=file) %>% 
  mutate(file_name=str_remove(file_name,".csv")) %>% 
  separate(file_name, into = c("arm","subject_id"),sep="_") %>% arrange(arm,subject_id) %>% 
  select(subject_id, arm, everything())
  
 file_data %>% 
   knitr::kable()
```

```{r}
file_data_week=file_data %>% 
  pivot_longer(week_1:week_8,
               names_to="weeks",
               values_to = "values") %>% 
  separate(weeks, into = c("week","weeks"),sep = "_")

file_data_week %>% 
  ggplot(aes(x=weeks, y=values, group=subject_id, color=subject_id))+
  geom_line()+facet_grid(~arm) +
  labs(title = "Observations on each subject over time")
  
```

#comments

## problem 3

```{r}
set.seed(100)

sim_regression= function(beta1,n=30, beta0=2,sigma_squared=50){
  sim_data= tibble(
    x=rnorm(n,mean=0, sd=1),
    y=beta0+beta1*x+rnorm(n,mean=0,sd=sqrt(sigma_squared))
  )
  
  ls_fit= lm(y~x, data=sim_data) %>% 
    broom::tidy() %>% 
    select(term, estimate, p.value) %>% 
    mutate(term=recode(term, "x"="beta1_hat")) %>% 
    filter(term=="beta1_hat") 
  
}
```

```{r}
sim_results=
  rerun(10000, sim_regression(beta1=0)) %>%bind_rows()
```

```{r}
sim_results16= 
  tibble(beta1=c(1:6)) %>% 
  mutate(model= map(beta1,~rerun(100, sim_regression(beta1=.x)))) %>% 
  unnest() %>% 
  unnest
```

```{r}
sim_results16 %>% 
  group_by(beta1) %>% 
  summarise(total=n(),
            alpha=sum(p.value<0.05)/total) %>% ggplot(aes(y=alpha, x=beta1)) +geom_point()+geom_line()+labs(title = "Association between effect size and power", x= "effect size(beta 1)", y= "power")

  
```

```{r}
average = 
  sim_results16 %>% 
  pivot_wider(names_from = term,
              values_from = estimate) %>% 
  group_by(beta1) %>% 
  summarise(avg_beta=mean(beta1_hat))
```

```{r}
null_reject =
  sim_results16 %>% 
  pivot_wider(names_from = term,
              values_from = estimate) %>% 
  filter(p.value<0.05) %>% 
  group_by(beta1) %>% 
  summarise(avg_beta_null=mean(beta1_hat))
```

```{r}
average %>% ggplot(aes(x=beta1, y=avg_beta))+ geom_point()+geom_smooth()

null_reject %>% ggplot(aes(x=beta1, y=avg_beta_null))+ geom_point()+geom_smooth()
```




















